version: "3"
services:
  web-server:
    build:
      dockerfile: epilearn.Dockerfile
      context: .
    restart: always
    volumes:
      - "./app:/var/www/html/"
    ports:
      - "8080:80"
      
